title: "Kush Saraiya"
description: "Seasoned Software Consultant · Bridge Between Tech & Product"
baseurl: ""
url: "https://saraiyakush.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
